name: Test Manifest Sync

on: [workflow_dispatch]

jobs:
  test-sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install repo
        run: |
          sudo wget -q https://storage.googleapis.com/git-repo-downloads/repo -O /usr/local/bin/repo
          sudo chmod a+x /usr/local/bin/repo
          repo --version

      - name: Free space before
        run: df -h /

      - name: Repo init
        run: |
          git config --global user.name "ci"
          git config --global user.email "ci@ci.com"
          repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-18.1

      - name: Copy local manifest
        run: |
          mkdir -p .repo/local_manifests
          cp local_manifest.xml .repo/local_manifests/

      - name: Repo sync
        run: |
          repo sync --force-sync -c --no-tags --optimized-fetch --prune -j$(nproc)

      - name: Free space after
        run: df -h /

      - name: Source size
        run: |
          du -sh --exclude=.git
